### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by davidkarl** [anderskm/gputil#20] opened 2018-12-08 12:15 UTC
hi, 
i pip installed the package and tried running GPUtil.getAvailable() but got the bellow listed massage. any thought?

thank you very much for this package.

GPUtil.getAvailable()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\dkarl\AppData\Local\conda\conda\envs\dudy_test\lib\site-packages\GPUtil\GPUtil.py", line 123, in getAvailable
    GPUs = getGPUs()
  File "C:\Users\dkarl\AppData\Local\conda\conda\envs\dudy_test\lib\site-packages\GPUtil\GPUtil.py", line 64, in getGPUs
    p = Popen(["nvidia-smi","--query-gpu=index,uuid,utilization.gpu,memory.total,memory.used,memory.free,driver_version,name,gpu_serial,display_active,display_mode", "--format=csv,noheader,nounits"], stdout=PIPE)
  File "C:\Users\dkarl\AppData\Local\conda\conda\envs\dudy_test\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\dkarl\AppData\Local\conda\conda\envs\dudy_test\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by anderskm** [comment] 2018-12-08 12:45
Are you using the version on pip or are you using the latest version here on github? The version here in github is a few features ahead of pip.
The issue is caused by nvidia-smi not being in your environment variable "path". This should be corrected in the current version here on Github, but not on pip.

To solve the problem, you can either download the code here or add the folder with nvidia-smi to your environment variable "path".

The issue have been previously discussed. You can have a look at [the original issue](https://github.com/anderskm/gputil/issues/8) and the [pull request](https://github.com/anderskm/gputil/pull/17) solving it.

Hopefully, I will get time to push the newest version to pip before Christmas :-)

**Comment by davidkarl** [comment] 2018-12-08 13:18
thank you very much,
what i did is simply use the github version and it worked.

however, for completeness' sake - i actually figured out that adding nvidia-smi to path was the problem however i guess i don't know enough because i tried going to "user variables" and "system variables" and to both of them i added:
variable: nvidia-smi
value: C:\Program Files\NVIDIA Corporation\NVSMI     (path to the nvidia-smi.exe)

however that didn't work with the pip version.

should i have done something else in my environment variables window?

**Comment by anderskm** [comment] 2018-12-18 09:27
@davidkarl The pip version have been quite a bit behind the github version in terms of features. I have simply been too slow to push the new features/fixes to pip.
However, I have [tagged and released a new version (v1.4.0)](https://github.com/anderskm/gputil/releases/tag/v1.4.0) and uploaded it to [pip](https://pypi.org/project/GPUtil/).

W.r.t. your issue with the environment variables, you should add `C:\Program Files\NVIDIA Corporation\NVSMI` to the variable called `PATH`. But that should no longer be required with the latest version on pip (and github).

I will be closing this issue for now. If the problem still remains, feel free to comment on this issue, and I will reopen it.

**Closed by anderskm** 2018-12-18 09:27 UTC
